### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by dually8** [dually8/godot-projects#1]
- [ ] Create releases of all games
- [x] ~~[Learn how to sign releases](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_windows.html)~~ Not doing this because it's too expensive lol
- [ ] Create help menu for all games that show the controls
- [x] Learn how to do controls like Unreal Engine (like how it has "Jump", "Forward", etc. in the options and you can assign multiple keys to it)

**Comment by dually8** [comment]
For doing controls like Unreal Engine: https://www.youtube.com/watch?v=ngHbAmN062c

Use something like `Input.is_action_pressed("ui_left")`

See also: https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html

**Comment by dually8** [comment]
I may not end up doing the signed releases because it's evidently $1000+ to get a signing certificate from an certificate authority 😭
